/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ql;

/**
 *
 * @author kerim
 */
public class QLForm extends javax.swing.JFrame {

    /**
     * Creates new form QLForm
     */
    public QLForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        questionLabel1 = new javax.swing.JLabel();
        questionValue1 = new javax.swing.JCheckBox();
        questionLabel2 = new javax.swing.JLabel();
        questionValue2 = new javax.swing.JTextField();
        questionLabel3 = new javax.swing.JLabel();
        questionValue3 = new javax.swing.JSpinner();
        questionLabel4 = new javax.swing.JLabel();
        questionValue4 = new javax.swing.JCheckBox();
        questionLabel5 = new javax.swing.JLabel();
        questionValue5 = new javax.swing.JTextField();
        questionLabel6 = new javax.swing.JLabel();
        questionValue6 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("form name");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 20, 15));

        questionLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        questionLabel1.setText("House was build:");
        jPanel1.add(questionLabel1);
        jPanel1.add(questionValue1);

        questionLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        questionLabel2.setText("House was build:");
        jPanel1.add(questionLabel2);
        jPanel1.add(questionValue2);

        questionLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        questionLabel3.setText("House was build:");
        jPanel1.add(questionLabel3);
        jPanel1.add(questionValue3);

        questionLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        questionLabel4.setText("House was build:");
        jPanel1.add(questionLabel4);

        questionValue4.setEnabled(false);
        jPanel1.add(questionValue4);

        questionLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        questionLabel5.setText("House was build:");
        jPanel1.add(questionLabel5);

        questionValue5.setEnabled(false);
        jPanel1.add(questionValue5);

        questionLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        questionLabel6.setText("House was build:");
        jPanel1.add(questionLabel6);

        questionValue6.setEnabled(false);
        jPanel1.add(questionValue6);
        jPanel1.add(jPanel2);

        jButton1.setText("Save");
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel questionLabel1;
    private javax.swing.JLabel questionLabel2;
    private javax.swing.JLabel questionLabel3;
    private javax.swing.JLabel questionLabel4;
    private javax.swing.JLabel questionLabel5;
    private javax.swing.JLabel questionLabel6;
    private javax.swing.JCheckBox questionValue1;
    private javax.swing.JTextField questionValue2;
    private javax.swing.JSpinner questionValue3;
    private javax.swing.JCheckBox questionValue4;
    private javax.swing.JTextField questionValue5;
    private javax.swing.JSpinner questionValue6;
    // End of variables declaration//GEN-END:variables
}
