package org.uva.sea.ql;

import org.uva.sea.ql.ast.*;
import org.uva.sea.ql.ast.expr.Add;
import org.uva.sea.ql.ast.expr.And;
import org.uva.sea.ql.ast.expr.Bool;
import org.uva.sea.ql.ast.expr.Div;
import org.uva.sea.ql.ast.expr.Eq;
import org.uva.sea.ql.ast.expr.GEq;
import org.uva.sea.ql.ast.expr.GT;
import org.uva.sea.ql.ast.expr.Ident;
import org.uva.sea.ql.ast.expr.If;
import org.uva.sea.ql.ast.expr.Int;
import org.uva.sea.ql.ast.expr.LEq;
import org.uva.sea.ql.ast.expr.LT;
import org.uva.sea.ql.ast.expr.Mul;
import org.uva.sea.ql.ast.expr.NEq;
import org.uva.sea.ql.ast.expr.Neg;
import org.uva.sea.ql.ast.expr.Not;
import org.uva.sea.ql.ast.expr.Or;
import org.uva.sea.ql.ast.expr.Pos;
import org.uva.sea.ql.ast.expr.Str;
import org.uva.sea.ql.ast.expr.Sub;

public interface ASTNodeVisitor<ReturnType, ParameterType> {
	public ReturnType visit(Add         astNode, ParameterType param);
	public ReturnType visit(And         astNode, ParameterType param);
	public ReturnType visit(Bool        astNode, ParameterType param);
	public ReturnType visit(Computed    astNode, ParameterType param);
	public ReturnType visit(Declaration astNode, ParameterType param);
	public ReturnType visit(Div         astNode, ParameterType param);
	public ReturnType visit(Eq          astNode, ParameterType param);
	public ReturnType visit(Form        astNode, ParameterType param);
	public ReturnType visit(GEq         astNode, ParameterType param);
	public ReturnType visit(GT          astNode, ParameterType param);
	public ReturnType visit(Ident       astNode, ParameterType param);
	public ReturnType visit(If          astNode, ParameterType param);
	public ReturnType visit(Int         astNode, ParameterType param);
	public ReturnType visit(LEq         astNode, ParameterType param);
	public ReturnType visit(LT          astNode, ParameterType param);
	public ReturnType visit(Mul         astNode, ParameterType param);
	public ReturnType visit(Neg         astNode, ParameterType param);
	public ReturnType visit(NEq         astNode, ParameterType param);
	public ReturnType visit(Not         astNode, ParameterType param);
	public ReturnType visit(Or          astNode, ParameterType param);
	public ReturnType visit(Pos         astNode, ParameterType param);
	public ReturnType visit(Question    astNode, ParameterType param);
	public ReturnType visit(Str         astNode, ParameterType param);
	public ReturnType visit(Sub         astNode, ParameterType param);
}
